# Generated by Django 4.0.6 on 2022-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_birthday_date_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=9),
        ),
    ]
