# Generated by Django 4.0.6 on 2022-07-05 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.host'),
        ),
        migrations.AddField(
            model_name='room',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.region'),
        ),
        migrations.AddField(
            model_name='room',
            name='types',
            field=models.ManyToManyField(db_table='room_types', to='rooms.type'),
        ),
    ]
