# Generated by Django 4.0.6 on 2022-07-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.CharField(max_length=45),
        ),
    ]
