# Generated by Django 4.0.6 on 2022-07-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_number', models.CharField(max_length=14)),
                ('accomodation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('num_of_guest', models.IntegerField()),
                ('num_of_pet', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'reservation_tatus',
            },
        ),
    ]
