# Generated by Django 4.0.6 on 2022-07-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservationstatus',
            table='reservation_status',
        ),
    ]
