# Generated by Django 4.0.6 on 2022-07-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=500)),
                ('review_img', models.CharField(max_length=1000)),
                ('ratings', models.DecimalField(decimal_places=2, default=3.0, max_digits=2)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
